
services:
  api:
    build: .
    ports:
      - "8000:8000"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/leadgen
    depends_on:
      - db
    restart: always

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leadgen
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  
  redis:
    image: redis:7
    ports:
      - "6379:6379"


  worker:
    build: .
    command: celery -A app.worker.celery_app worker --loglevel=info
    depends_on:
      - redis
      - db
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/leadgen
    restart: always

volumes:
  postgres_data:
