"""initial tables

Revision ID: b823eff83684
Revises: 
Create Date: 2026-03-02 17:25:57.141451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b823eff83684'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_businesses_place_id'), table_name='businesses')
    op.create_index(op.f('ix_businesses_place_id'), 'businesses', ['place_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_businesses_place_id'), table_name='businesses')
    op.create_index(op.f('ix_businesses_place_id'), 'businesses', ['place_id'], unique=True)
    # ### end Alembic commands ###
